# -*- coding: utf-8 -*-
"""Computer vision 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G0saNdXdNhKo-0L4UIKdYbIuq5JWi-Ga

# Welcome to Colab!
"""

from google.colab import drive
drive.mount('/content/drive')

import os

base_path = "/content/drive/MyDrive"

for item in os.listdir(base_path):
    print(item)

import os

image_folder = "/content/drive/MyDrive/ISIC2018_Task1-2_Training_Input"
mask_folder = "/content/drive/MyDrive/ISIC2018_Task1_Training_GroundTruth"

images = [
    f for f in os.listdir(image_folder)
    if f.lower().endswith((".jpg", ".jpeg"))
]

masks = [
    f for f in os.listdir(mask_folder)
    if f.lower().endswith((".png", ".jpg", ".jpeg"))
]

print("Number of images:", len(images))
print("Number of masks:", len(masks))

print("\nFirst 5 images:")
print(images[:5])

print("\nFirst 5 masks:")
print(masks[:5])

import os

base_path = "/content/drive/MyDrive"

for folder in [
    "ISIC2018_Task1-2_Training_Input",
    "ISIC2018_Task1_Training_GroundTruth"
]:
    path = os.path.join(base_path, folder)

    print("\n==============================")
    print(folder)
    print("==============================")

    for root, dirs, files in os.walk(path):
        print("Folder:", root)
        print("Files:", files[:5])
        print("Number of files:", len(files))



import os

image_folder = "/content/drive/MyDrive/ISIC2018_Task1-2_Training_Input/ISIC2018_Task1-2_Training_Input"
mask_folder = "/content/drive/MyDrive/ISIC2018_Task1_Training_GroundTruth/ISIC2018_Task1_Training_GroundTruth"

# Get image and mask files
images = sorted([
    f for f in os.listdir(image_folder)
    if f.lower().endswith(".jpg")
])

masks = sorted([
    f for f in os.listdir(mask_folder)
    if f.lower().endswith(".png")
])

print("Number of images:", len(images))
print("Number of masks:", len(masks))

print("\nFirst 5 images:")
for f in images[:5]:
    print(f)

print("\nFirst 5 masks:")
for f in masks[:5]:
    print(f)

from PIL import Image
import matplotlib.pyplot as plt
import os

image_name = images[0]

mask_name = image_name.replace(".jpg", "_segmentation.png")

image = Image.open(os.path.join(image_folder, image_name))
mask = Image.open(os.path.join(mask_folder, mask_name))

plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.imshow(image)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(mask, cmap="gray")
plt.title("Ground Truth Mask")
plt.axis("off")

plt.show()

from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import os
images = sorted([f for f in os.listdir(image_folder) if f.lower().endswith(".jpg")])

image_name = images[0]
mask_name = image_name.replace(".jpg", "_segmentation.png")

image = Image.open(os.path.join(image_folder, image_name)).convert("RGB")
mask = Image.open(os.path.join(mask_folder, mask_name)).convert("L")

image_resized = image.resize((256, 256))
mask_resized = mask.resize((256, 256), Image.NEAREST)

image_array = np.array(image_resized) / 255.0

mask_array = np.array(mask_resized)
mask_binary = (mask_array > 127).astype(np.uint8)

print("Original image size:", image.size)
print("Resized image size:", image_resized.size)
print("Mask size:", mask_resized.size)
print("Image pixel range:", image_array.min(), "to", image_array.max())
print("Mask values:", np.unique(mask_binary))

plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.imshow(image_array)
plt.title("Resized and Normalized Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(mask_binary, cmap="gray")
plt.title("Resized Binary Mask")
plt.axis("off")

plt.show()

from sklearn.model_selection import train_test_split

pairs = []

for image_name in images:
    mask_name = image_name.replace(".jpg", "_segmentation.png")

    if mask_name in masks:
        pairs.append((image_name, mask_name))

print("Total matched pairs:", len(pairs))

train_pairs, temp_pairs = train_test_split(
    pairs,
    test_size=0.30,
    random_state=42
)

val_pairs, test_pairs = train_test_split(
    temp_pairs,
    test_size=0.50,
    random_state=42
)

print("Training pairs:", len(train_pairs))
print("Validation pairs:", len(val_pairs))
print("Test pairs:", len(test_pairs))
print("Total pairs:", len(train_pairs) + len(val_pairs) + len(test_pairs))

import random
from PIL import Image
import matplotlib.pyplot as plt
import os

# Select 3 random image-mask pairs
random_pairs = random.sample(pairs, 3)

plt.figure(figsize=(10, 9))

for i, (image_name, mask_name) in enumerate(random_pairs):

    image = Image.open(os.path.join(image_folder, image_name))
    mask = Image.open(os.path.join(mask_folder, mask_name))

    plt.subplot(3, 2, 2*i + 1)
    plt.imshow(image)
    plt.title("Original Image")
    plt.axis("off")

    plt.subplot(3, 2, 2*i + 2)
    plt.imshow(mask, cmap="gray")
    plt.title("Ground Truth Mask")
    plt.axis("off")

plt.tight_layout()
plt.show()

import torch
import torch.nn as nn

# Double convolution block
class DoubleConv(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()

        self.block = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, 3, padding=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, 3, padding=1),
            nn.ReLU(inplace=True)
        )

    def forward(self, x):
        return self.block(x)


# Baseline U-Net
class UNet(nn.Module):
    def __init__(self):
        super().__init__()

        # Encoder
        self.enc1 = DoubleConv(3, 64)
        self.enc2 = DoubleConv(64, 128)
        self.enc3 = DoubleConv(128, 256)
        self.enc4 = DoubleConv(256, 512)

        self.pool = nn.MaxPool2d(2)

        # Bottleneck
        self.bottleneck = DoubleConv(512, 1024)

        # Decoder
        self.up4 = nn.ConvTranspose2d(1024, 512, 2, stride=2)
        self.dec4 = DoubleConv(1024, 512)

        self.up3 = nn.ConvTranspose2d(512, 256, 2, stride=2)
        self.dec3 = DoubleConv(512, 256)

        self.up2 = nn.ConvTranspose2d(256, 128, 2, stride=2)
        self.dec2 = DoubleConv(256, 128)

        self.up1 = nn.ConvTranspose2d(128, 64, 2, stride=2)
        self.dec1 = DoubleConv(128, 64)

        # Output layer
        self.output = nn.Conv2d(64, 1, 1)

    def forward(self, x):

        # Encoder
        e1 = self.enc1(x)
        e2 = self.enc2(self.pool(e1))
        e3 = self.enc3(self.pool(e2))
        e4 = self.enc4(self.pool(e3))

        # Bottleneck
        b = self.bottleneck(self.pool(e4))

        # Decoder
        d4 = self.up4(b)
        d4 = torch.cat([d4, e4], dim=1)
        d4 = self.dec4(d4)

        d3 = self.up3(d4)
        d3 = torch.cat([d3, e3], dim=1)
        d3 = self.dec3(d3)

        d2 = self.up2(d3)
        d2 = torch.cat([d2, e2], dim=1)
        d2 = self.dec2(d2)

        d1 = self.up1(d2)
        d1 = torch.cat([d1, e1], dim=1)
        d1 = self.dec1(d1)

        return self.output(d1)


# Create the model
model = UNet()

# Test with a dummy 256x256 RGB image
test_input = torch.randn(1, 3, 256, 256)

with torch.no_grad():
    test_output = model(test_input)

print("Input shape:", test_input.shape)
print("Output shape:", test_output.shape)

# Calculate trainable parameters

total_params = sum(
    p.numel() for p in model.parameters() if p.requires_grad
)

print("Total trainable parameters:", total_params)
print("Total parameters in millions:", round(total_params / 1e6, 2), "M")

import torch
import torch.nn as nn

class ResidualBlock(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()

        self.conv1 = nn.Conv2d(in_channels, out_channels, 3, padding=1)
        self.bn1 = nn.BatchNorm2d(out_channels)

        self.conv2 = nn.Conv2d(out_channels, out_channels, 3, padding=1)
        self.bn2 = nn.BatchNorm2d(out_channels)

        self.relu = nn.ReLU(inplace=True)

        if in_channels != out_channels:
            self.shortcut = nn.Conv2d(in_channels, out_channels, 1)
        else:
            self.shortcut = nn.Identity()

    def forward(self, x):
        identity = self.shortcut(x)

        out = self.relu(self.bn1(self.conv1(x)))
        out = self.bn2(self.conv2(out))

        out = out + identity
        out = self.relu(out)

        return out

class AttentionGate(nn.Module):
    def __init__(self, gating_channels, skip_channels, inter_channels):
        super().__init__()

        self.gating = nn.Conv2d(gating_channels, inter_channels, 1)
        self.skip = nn.Conv2d(skip_channels, inter_channels, 1)

        self.attention = nn.Sequential(
            nn.ReLU(inplace=True),
            nn.Conv2d(inter_channels, 1, 1),
            nn.Sigmoid()
        )

    def forward(self, gating, skip):
        g = self.gating(gating)
        x = self.skip(skip)

        attention_map = self.attention(g + x)

        return skip * attention_map

class ResidualAttentionUNet(nn.Module):
    def __init__(self):
        super().__init__()

        self.enc1 = ResidualBlock(3, 64)
        self.enc2 = ResidualBlock(64, 128)
        self.enc3 = ResidualBlock(128, 256)
        self.enc4 = ResidualBlock(256, 512)

        self.pool = nn.MaxPool2d(2)

        self.bottleneck = ResidualBlock(512, 1024)

        self.up4 = nn.ConvTranspose2d(1024, 512, 2, stride=2)
        self.att4 = AttentionGate(512, 512, 256)
        self.dec4 = ResidualBlock(1024, 512)

        self.up3 = nn.ConvTranspose2d(512, 256, 2, stride=2)
        self.att3 = AttentionGate(256, 256, 128)
        self.dec3 = ResidualBlock(512, 256)

        self.up2 = nn.ConvTranspose2d(256, 128, 2, stride=2)
        self.att2 = AttentionGate(128, 128, 64)
        self.dec2 = ResidualBlock(256, 128)

        self.up1 = nn.ConvTranspose2d(128, 64, 2, stride=2)
        self.att1 = AttentionGate(64, 64, 32)
        self.dec1 = ResidualBlock(128, 64)

        self.output = nn.Conv2d(64, 1, 1)

    def forward(self, x):

        e1 = self.enc1(x)
        e2 = self.enc2(self.pool(e1))
        e3 = self.enc3(self.pool(e2))
        e4 = self.enc4(self.pool(e3))

        b = self.bottleneck(self.pool(e4))

        d4 = self.up4(b)
        a4 = self.att4(d4, e4)
        d4 = torch.cat([d4, a4], dim=1)
        d4 = self.dec4(d4)

        d3 = self.up3(d4)
        a3 = self.att3(d3, e3)
        d3 = torch.cat([d3, a3], dim=1)
        d3 = self.dec3(d3)

        d2 = self.up2(d3)
        a2 = self.att2(d2, e2)
        d2 = torch.cat([d2, a2], dim=1)
        d2 = self.dec2(d2)

        d1 = self.up1(d2)
        a1 = self.att1(d1, e1)
        d1 = torch.cat([d1, a1], dim=1)
        d1 = self.dec1(d1)

        return self.output(d1)

proposed_model = ResidualAttentionUNet()

test_input = torch.randn(1, 3, 256, 256)

with torch.no_grad():
    proposed_output = proposed_model(test_input)

print("Input shape:", test_input.shape)
print("Proposed model output shape:", proposed_output.shape)

proposed_params = sum(
    p.numel() for p in proposed_model.parameters()
    if p.requires_grad
)

print("Proposed model trainable parameters:", proposed_params)
print("Proposed model parameters in millions:",
      round(proposed_params / 1e6, 2), "M")

print("\nBaseline U-Net parameters:", total_params)
print("Baseline U-Net parameters in millions:",
      round(total_params / 1e6, 2), "M")

import torch
import torch.nn as nn


# Dice loss
def dice_loss(pred, target, smooth=1):
    pred = torch.sigmoid(pred)

    pred = pred.view(-1)
    target = target.view(-1)

    intersection = (pred * target).sum()

    dice = (2.0 * intersection + smooth) / (
        pred.sum() + target.sum() + smooth
    )

    return 1 - dice


# Combined BCE + Dice loss
def combined_loss(pred, target):
    bce = nn.BCEWithLogitsLoss()(pred, target)
    dice = dice_loss(pred, target)

    return bce + dice


# Training function
def train_one_epoch(model, loader, optimizer, device):

    model.train()

    total_loss = 0

    for images_batch, masks_batch in loader:

        images_batch = images_batch.to(device)
        masks_batch = masks_batch.to(device)

        # Clear previous gradients
        optimizer.zero_grad()

        # Forward pass
        predictions = model(images_batch)

        # Calculate loss
        loss = combined_loss(predictions, masks_batch)

        # Backpropagation
        loss.backward()

        # Update model parameters
        optimizer.step()

        total_loss += loss.item()

    return total_loss / len(loader)


# Validation function
def validate(model, loader, device):

    model.eval()

    total_loss = 0

    with torch.no_grad():

        for images_batch, masks_batch in loader:

            images_batch = images_batch.to(device)
            masks_batch = masks_batch.to(device)

            predictions = model(images_batch)

            loss = combined_loss(predictions, masks_batch)

            total_loss += loss.item()

    return total_loss / len(loader)


# Select GPU if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Training device:", device)



import torch
from torch.utils.data import Dataset, DataLoader
from PIL import Image
import numpy as np
import os


class ISICDataset(Dataset):
    def __init__(self, pairs):
        self.pairs = pairs

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, index):

        image_name, mask_name = self.pairs[index]

        image = Image.open(
            os.path.join(image_folder, image_name)
        ).convert("RGB")

        mask = Image.open(
            os.path.join(mask_folder, mask_name)
        ).convert("L")

        # Resize
        image = image.resize((256, 256))
        mask = mask.resize((256, 256), Image.NEAREST)

        # Normalize image
        image = np.array(image, dtype=np.float32) / 255.0
        image = torch.tensor(image).permute(2, 0, 1)

        # Binary mask
        mask = np.array(mask, dtype=np.float32)
        mask = (mask > 127).astype(np.float32)
        mask = torch.tensor(mask).unsqueeze(0)

        return image, mask


# Create datasets
train_dataset = ISICDataset(train_pairs)
val_dataset = ISICDataset(val_pairs)
test_dataset = ISICDataset(test_pairs)


# Create DataLoaders
train_loader = DataLoader(
    train_dataset,
    batch_size=8,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=8,
    shuffle=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=8,
    shuffle=False
)


print("Training samples:", len(train_dataset))
print("Validation samples:", len(val_dataset))
print("Test samples:", len(test_dataset))

print("DataLoaders created successfully.")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Training device:", device)





import os
from PIL import Image
from tqdm import tqdm

# Local folders in Colab
local_image_folder = "/content/ISIC_images"
local_mask_folder = "/content/ISIC_masks"

os.makedirs(local_image_folder, exist_ok=True)
os.makedirs(local_mask_folder, exist_ok=True)

# Preprocess all matched image-mask pairs
for image_name, mask_name in tqdm(pairs):

    image_path = os.path.join(image_folder, image_name)
    mask_path = os.path.join(mask_folder, mask_name)

    # Load
    image = Image.open(image_path).convert("RGB")
    mask = Image.open(mask_path).convert("L")

    # Resize
    image = image.resize((256, 256))
    mask = mask.resize((256, 256), Image.NEAREST)

    # Save locally
    image.save(
        os.path.join(local_image_folder, image_name),
        quality=90
    )

    mask.save(
        os.path.join(local_mask_folder, mask_name)
    )

print("Local preprocessing completed.")

class ISICLocalDataset(Dataset):

    def __init__(self, pairs):
        self.pairs = pairs

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, index):

        image_name, mask_name = self.pairs[index]

        image = Image.open(
            os.path.join(local_image_folder, image_name)
        ).convert("RGB")

        mask = Image.open(
            os.path.join(local_mask_folder, mask_name)
        ).convert("L")

        # Convert image to tensor and normalize
        image = np.array(image, dtype=np.float32) / 255.0
        image = torch.tensor(image).permute(2, 0, 1)

        # Convert mask to binary tensor
        mask = np.array(mask, dtype=np.float32)
        mask = (mask > 127).astype(np.float32)
        mask = torch.tensor(mask).unsqueeze(0)

        return image, mask


train_dataset = ISICLocalDataset(train_pairs)
val_dataset = ISICLocalDataset(val_pairs)
test_dataset = ISICLocalDataset(test_pairs)

train_loader = DataLoader(
    train_dataset,
    batch_size=8,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=8,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=8,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

print("Training samples:", len(train_dataset))
print("Validation samples:", len(val_dataset))
print("Test samples:", len(test_dataset))
print("Local DataLoaders ready.")

# Test one training batch

images_batch, masks_batch = next(iter(train_loader))

images_batch = images_batch.to(device)
masks_batch = masks_batch.to(device)

print("Image batch shape:", images_batch.shape)
print("Mask batch shape:", masks_batch.shape)
print("Device:", images_batch.device)

# Train the baseline U-Net

epochs = 10
learning_rate = 0.001

model = model.to(device)

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=learning_rate
)

train_losses = []
val_losses = []

for epoch in range(epochs):

    train_loss = train_one_epoch(
        model,
        train_loader,
        optimizer,
        device
    )

    val_loss = validate(
        model,
        val_loader,
        device
    )

    train_losses.append(train_loss)
    val_losses.append(val_loss)

    print(
        f"Epoch [{epoch + 1}/{epochs}] "
        f"Training Loss: {train_loss:.4f} "
        f"Validation Loss: {val_loss:.4f}"
    )

# Train the proposed Residual + Attention U-Net

epochs = 10
learning_rate = 0.001

proposed_model = proposed_model.to(device)

proposed_optimizer = torch.optim.Adam(
    proposed_model.parameters(),
    lr=learning_rate
)

proposed_train_losses = []
proposed_val_losses = []

for epoch in range(epochs):

    train_loss = train_one_epoch(
        proposed_model,
        train_loader,
        proposed_optimizer,
        device
    )

    val_loss = validate(
        proposed_model,
        val_loader,
        device
    )

    proposed_train_losses.append(train_loss)
    proposed_val_losses.append(val_loss)

    print(
        f"Epoch [{epoch + 1}/{epochs}] "
        f"Training Loss: {train_loss:.4f} "
        f"Validation Loss: {val_loss:.4f}"
    )

import os
import numpy as np
import torch
import matplotlib.pyplot as plt

results_folder = "/content/drive/MyDrive/ISIC2018_Segmentation_Results"
os.makedirs(results_folder, exist_ok=True)

torch.save(
    model.state_dict(),
    os.path.join(results_folder, "baseline_unet.pth")
)

torch.save(
    proposed_model.state_dict(),
    os.path.join(results_folder, "proposed_residual_attention_unet.pth")
)

np.savez(
    os.path.join(results_folder, "training_history.npz"),
    baseline_train_loss=np.array(train_losses),
    baseline_val_loss=np.array(val_losses),
    proposed_train_loss=np.array(proposed_train_losses),
    proposed_val_loss=np.array(proposed_val_losses)
)

plt.figure(figsize=(10, 5))

plt.plot(train_losses, label="Baseline Training")
plt.plot(val_losses, label="Baseline Validation")
plt.plot(proposed_train_losses, label="Proposed Training")
plt.plot(proposed_val_losses, label="Proposed Validation")

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training and Validation Loss")
plt.legend()
plt.grid(True)

plt.savefig(
    os.path.join(results_folder, "training_loss_comparison.png"),
    dpi=300,
    bbox_inches="tight"
)

plt.show()

print("Training results saved successfully.")
print("Results folder:", results_folder)
print("\nSaved files:")
for file in os.listdir(results_folder):
    print("-", file)

# Move both trained models to the GPU

model = model.to(device)
proposed_model = proposed_model.to(device)

model.eval()
proposed_model.eval()

print("Baseline model device:", next(model.parameters()).device)
print("Proposed model device:", next(proposed_model.parameters()).device)
print("Test device:", device)

import torch

def calculate_metrics(model, loader, device, threshold=0.5):
    model.eval()

    total_dice = 0
    total_iou = 0
    total_precision = 0
    count = 0

    with torch.no_grad():

        for images, masks in loader:

            images = images.to(device)
            masks = masks.to(device)

            outputs = torch.sigmoid(model(images))
            predictions = (outputs > threshold).float()

            predictions = predictions.view(predictions.size(0), -1)
            masks = masks.view(masks.size(0), -1)

            intersection = (predictions * masks).sum(dim=1)

            prediction_area = predictions.sum(dim=1)
            mask_area = masks.sum(dim=1)

            union = prediction_area + mask_area - intersection

            true_positive = intersection
            false_positive = (predictions * (1 - masks)).sum(dim=1)

            dice = (2 * intersection + 1e-7) / (
                prediction_area + mask_area + 1e-7
            )

            iou = (intersection + 1e-7) / (union + 1e-7)

            precision = (true_positive + 1e-7) / (
                true_positive + false_positive + 1e-7
            )

            total_dice += dice.sum().item()
            total_iou += iou.sum().item()
            total_precision += precision.sum().item()

            count += images.size(0)

    return (
        total_dice / count,
        total_iou / count,
        total_precision / count
    )


baseline_dice, baseline_iou, baseline_precision = calculate_metrics(
    model,
    test_loader,
    device
)

proposed_dice, proposed_iou, proposed_precision = calculate_metrics(
    proposed_model,
    test_loader,
    device
)

print("Baseline U-Net")
print("Dice:", round(baseline_dice, 4))
print("IoU:", round(baseline_iou, 4))
print("Precision:", round(baseline_precision, 4))

print("\nProposed Residual + Attention U-Net")
print("Dice:", round(proposed_dice, 4))
print("IoU:", round(proposed_iou, 4))
print("Precision:", round(proposed_precision, 4))



# Check prediction probability ranges

images, masks = next(iter(test_loader))

images = images.to(device)
masks = masks.to(device)

with torch.no_grad():
    baseline_probs = torch.sigmoid(model(images))
    proposed_probs = torch.sigmoid(proposed_model(images))

print("Baseline probability:")
print("Minimum:", baseline_probs.min().item())
print("Maximum:", baseline_probs.max().item())
print("Mean:", baseline_probs.mean().item())

print("\nProposed model probability:")
print("Minimum:", proposed_probs.min().item())
print("Maximum:", proposed_probs.max().item())
print("Mean:", proposed_probs.mean().item())

print("\nGround truth foreground ratio:",
      masks.mean().item())

print("Baseline predicted foreground ratio:",
      (baseline_probs > 0.5).float().mean().item())

print("Proposed predicted foreground ratio:",
      (proposed_probs > 0.5).float().mean().item())

# Reload the trained model weights from Google Drive

baseline_path = "/content/drive/MyDrive/ISIC2018_Segmentation_Results/baseline_unet.pth"
proposed_path = "/content/drive/MyDrive/ISIC2018_Segmentation_Results/proposed_residual_attention_unet.pth"

model.load_state_dict(torch.load(baseline_path, map_location=device))
proposed_model.load_state_dict(torch.load(proposed_path, map_location=device))

model = model.to(device)
proposed_model = proposed_model.to(device)

model.eval()
proposed_model.eval()

print("Baseline trained weights loaded.")
print("Proposed trained weights loaded.")
print("Baseline device:", next(model.parameters()).device)
print("Proposed device:", next(proposed_model.parameters()).device)

import matplotlib.pyplot as plt
import torch

images, masks = next(iter(test_loader))

images = images.to(device)
masks = masks.to(device)

with torch.no_grad():
    baseline_output = torch.sigmoid(model(images))
    proposed_output = torch.sigmoid(proposed_model(images))

baseline_prediction = (baseline_output[0] > 0.5).float()
proposed_prediction = (proposed_output[0] > 0.5).float()

image = images[0].cpu().permute(1, 2, 0)
ground_truth = masks[0].cpu().squeeze()
baseline_prediction = baseline_prediction.cpu().squeeze()
proposed_prediction = proposed_prediction.cpu().squeeze()

plt.figure(figsize=(12, 8))

plt.subplot(2, 2, 1)
plt.imshow(image)
plt.title("Original Image")
plt.axis("off")

plt.subplot(2, 2, 2)
plt.imshow(ground_truth, cmap="gray")
plt.title("Ground Truth")
plt.axis("off")

plt.subplot(2, 2, 3)
plt.imshow(baseline_prediction, cmap="gray")
plt.title("Baseline U-Net Prediction")
plt.axis("off")

plt.subplot(2, 2, 4)
plt.imshow(proposed_prediction, cmap="gray")
plt.title("Proposed Model Prediction")
plt.axis("off")

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

# Store pixel-level results
baseline_true = []
baseline_pred = []

proposed_true = []
proposed_pred = []

# Evaluate on the complete test set
with torch.no_grad():

    for images, masks in test_loader:

        images = images.to(device)
        masks = masks.to(device)

        # Predictions from both models
        baseline_output = torch.sigmoid(model(images))
        proposed_output = torch.sigmoid(proposed_model(images))

        baseline_prediction = (baseline_output > 0.5).int()
        proposed_prediction = (proposed_output > 0.5).int()

        # Store flattened pixel values
        baseline_true.extend(masks.cpu().numpy().flatten())
        baseline_pred.extend(baseline_prediction.cpu().numpy().flatten())

        proposed_true.extend(masks.cpu().numpy().flatten())
        proposed_pred.extend(proposed_prediction.cpu().numpy().flatten())


# Calculate confusion matrices
baseline_cm = confusion_matrix(
    baseline_true,
    baseline_pred
)

proposed_cm = confusion_matrix(
    proposed_true,
    proposed_pred
)

print("Baseline U-Net Confusion Matrix:")
print(baseline_cm)

print("\nProposed Residual + Attention U-Net Confusion Matrix:")
print(proposed_cm)


# Display confusion matrices
fig, axes = plt.subplots(1, 2, figsize=(10, 4))

axes[0].imshow(baseline_cm)
axes[0].set_title("Baseline U-Net")
axes[0].set_xlabel("Predicted")
axes[0].set_ylabel("Actual")

for i in range(2):
    for j in range(2):
        axes[0].text(j, i, baseline_cm[i, j],
                     ha="center", va="center")

axes[1].imshow(proposed_cm)
axes[1].set_title("Proposed Residual + Attention U-Net")
axes[1].set_xlabel("Predicted")
axes[1].set_ylabel("Actual")

for i in range(2):
    for j in range(2):
        axes[1].text(j, i, proposed_cm[i, j],
                     ha="center", va="center")

plt.tight_layout()
plt.show()

# Model comparison

baseline_params = total_params
proposed_params = proposed_params

# Calculate percentage improvements
dice_improvement = ((proposed_dice - baseline_dice) / baseline_dice) * 100
iou_improvement = ((proposed_iou - baseline_iou) / baseline_iou) * 100
precision_improvement = ((proposed_precision - baseline_precision) / baseline_precision) * 100
parameter_increase = ((proposed_params - baseline_params) / baseline_params) * 100

print("MODEL COMPARISON")
print("----------------")

print(f"Baseline Dice: {baseline_dice:.4f}")
print(f"Proposed Dice: {proposed_dice:.4f}")
print(f"Dice improvement: {dice_improvement:.2f}%")

print(f"\nBaseline IoU: {baseline_iou:.4f}")
print(f"Proposed IoU: {proposed_iou:.4f}")
print(f"IoU improvement: {iou_improvement:.2f}%")

print(f"\nBaseline Precision: {baseline_precision:.4f}")
print(f"Proposed Precision: {proposed_precision:.4f}")
print(f"Precision improvement: {precision_improvement:.2f}%")

print(f"\nBaseline parameters: {baseline_params:,}")
print(f"Proposed parameters: {proposed_params:,}")
print(f"Parameter increase: {parameter_increase:.2f}%")

"""Colab notebooks execute code on Google's cloud servers, meaning you can leverage the power of Google hardware, including [GPUs and TPUs](#using-accelerated-hardware), regardless of the power of your machine. All you need is a browser.

For example, if you find yourself waiting for **pandas** code to finish running and want to go faster, you can switch to a GPU Runtime and use libraries like [RAPIDS cuDF](https://rapids.ai/cudf-pandas) that provide zero-code-change acceleration.

To learn more about accelerating pandas on Colab, see the [10 minute guide](https://colab.research.google.com/github/rapidsai-community/showcase/blob/main/getting_started_tutorials/cudf_pandas_colab_demo.ipynb) or
 [US stock market data analysis demo](https://colab.research.google.com/github/rapidsai-community/showcase/blob/main/getting_started_tutorials/cudf_pandas_stocks_demo.ipynb).

<div class="markdown-google-sans">

## Machine learning
</div>

With Colab you can import an image dataset, train an image classifier on it, and evaluate the model, all in just [a few lines of code](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb).

Colab is used extensively in the machine learning community with applications including:
- Getting started with TensorFlow
- Developing and training neural networks
- Experimenting with TPUs
- Disseminating AI research
- Creating tutorials

To see sample Colab notebooks that demonstrate machine learning applications, see the [machine learning examples](#machine-learning-examples) below.

<div class="markdown-google-sans">

## More Resources

### Working with Notebooks in Colab

</div>

- [Overview of Colab](/notebooks/basic_features_overview.ipynb)
- [Guide to Markdown](/notebooks/markdown_guide.ipynb)
- [Importing libraries and installing dependencies](/notebooks/snippets/importing_libraries.ipynb)
- [Saving and loading notebooks in GitHub](https://colab.research.google.com/github/googlecolab/colabtools/blob/main/notebooks/colab-github-demo.ipynb)
- [Interactive forms](/notebooks/forms.ipynb)
- [Interactive widgets](/notebooks/widgets.ipynb)

<div class="markdown-google-sans">

<a name="working-with-data"></a>
### Working with Data
</div>

- [Loading data: Drive, Sheets, and Google Cloud Storage](/notebooks/io.ipynb)
- [Charts: visualizing data](/notebooks/charts.ipynb)
- [Getting started with BigQuery](/notebooks/bigquery.ipynb)

<div class="markdown-google-sans">

### Machine Learning

<div>

These are a few of the notebooks related to Machine Learning, including Google's online Machine Learning course. See the [full course website](https://developers.google.com/machine-learning/crash-course/) for more.
- [Intro to Pandas DataFrame](https://colab.research.google.com/github/google/eng-edu/blob/main/ml/cc/exercises/pandas_dataframe_ultraquick_tutorial.ipynb)
- [Intro to RAPIDS cuDF to accelerate pandas](https://nvda.ws/rapids-cudf)
- [Getting Started with cuML's accelerator mode](https://colab.research.google.com/github/rapidsai-community/showcase/blob/main/getting_started_tutorials/cuml_sklearn_colab_demo.ipynb)

<div class="markdown-google-sans">

<a name="using-accelerated-hardware"></a>
### Using Accelerated Hardware
</div>

- [Train a CNN to classify handwritten digits on the MNIST dataset using Flax NNX API](https://colab.research.google.com/github/google/flax/blob/main/docs_nnx/mnist_tutorial.ipynb)
- [Train a Vision Transformer (ViT) for image classification with JAX](https://colab.research.google.com/github/jax-ml/jax-ai-stack/blob/main/docs/source/JAX_Vision_transformer.ipynb)
- [Text classification with a transformer language model using JAX](https://colab.research.google.com/github/jax-ml/jax-ai-stack/blob/main/docs/source/JAX_transformer_text_classification.ipynb)

<div class="markdown-google-sans">

<a name="machine-learning-examples"></a>

### Featured examples

</div>

- [Train a miniGPT language model with JAX AI Stack](https://docs.jaxstack.ai/en/latest/JAX_for_LLM_pretraining.html)
- [LoRA/QLoRA finetuning for LLM using Tunix](https://github.com/google/tunix/blob/main/examples/qlora_gemma.ipynb)
- [Parameter-efficient fine-tuning of Gemma with LoRA and QLoRA](https://keras.io/examples/keras_recipes/parameter_efficient_finetuning_of_gemma_with_lora_and_qlora/)
- [Loading Hugging Face Transformers Checkpoints](https://keras.io/keras_hub/guides/hugging_face_keras_integration/)
- [8-bit Integer Quantization in Keras](https://keras.io/guides/int8_quantization_in_keras/)
- [Float8 training and inference with a simple Transformer model](https://keras.io/examples/keras_recipes/float8_training_and_inference_with_transformer/)
- [Pretraining a Transformer from scratch with KerasHub](https://keras.io/keras_hub/guides/transformer_pretraining/)
- [Simple MNIST convnet](https://keras.io/examples/vision/mnist_convnet/)
- [Image classification from scratch using Keras 3](https://keras.io/examples/vision/image_classification_from_scratch/)
- [Image Classification with KerasHub](https://keras.io/keras_hub/guides/classification_with_keras_hub/)
"""